// get all records
export const GET_ALL_MUSIC_FILE_REQUEST="GET_ALL_MUSIC_FILE_REQUEST"
export const GET_ALL_MUSIC_FILE_RESPONSE="GET_ALL_MUSIC_FILE_RESPONSE"

// store photo media files
export const GET_ALL_PHOTO_MEDIA_FILES="GET_ALL_PHOTO_MEDIA_FILES"
export const ADD_PHOTO_MEDIA_FILES="ADD_PHOTO_MEDIA_FILES"

